# Generated by Django 4.0.1 on 2022-02-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_studchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='crn',
            field=models.IntegerField(default=320),
            preserve_default=False,
        ),
    ]
